(* OCaml module generated by the BNF converter *)


type uIdent = UIdent of string
and lIdent = LIdent of string
and wild = Wild of string
and expr =
   Sequence of expr * expr
 | Application of expr * expr list
 | Supposition of pattern * expr * expr
 | Recurrence of pattern * expr * expr
 | Abstraction of pattern * expr
 | Condition of expr * expr * expr
 | Comprehension of binding list * expr
 | Consolidation of binding list * expr
 | Filtration of binding list * pattern list * expr
 | Concentration of binding list * pattern list * expr
 | Equation of expr * expr
 | ComparisonLT of expr * expr
 | ComparisonGT of expr * expr
 | ComparisonLTE of expr * expr
 | ComparisonGTE of expr * expr
 | Acquisition
 | Suspension of expr * expr
 | Release of expr * expr
 | InnerSuspension of expr * expr
 | Calculation of arithmeticExpr

and arithmeticExpr =
   Division of arithmeticExpr * arithmeticExpr
 | Addition of arithmeticExpr * arithmeticExpr
 | Multiplication of arithmeticExpr * arithmeticExpr
 | Juxtaposition of arithmeticExpr * arithmeticExpr
 | Negation of arithmeticExpr
 | Mention of variation
 | Actualization of value
 | Aggregation of expr

and binding =
   Question of pattern * expr

and pattern =
   Element of symbol * pattern list
 | Variable of variation
 | Materialization of value
 | Procession of lyst

and variation =
   Atomic of uIdent
 | Abandon of wild
 | Transcription of expr

and lyst =
   Empty
 | Enum of pattern list
 | Cons of pattern list * lyst
 | ConsV of pattern list * variation

and value =
   BooleanLiteral of duality
 | StringLiteral of string
 | IntegerLiteral of int
 | DoubleLiteral of float
 | Reification of expr

and duality =
   Verity
 | Absurdity

and symbol =
   Tag of lIdent

